name: Bug report
title: "[Bug] "
description: Something is not working in the extension
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Click on '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: A clear and concise description of what is happening.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots and/or a short video to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What version of the operating system(s) are you seeing the problem on?
  - type: dropdown
    id: browsers
    attributes:
      label: Web Browser
      description: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Microsoft Edge
        - Firefox
        - Opera
        - Brave
        - Vivaldi
        - Kiwi
        - Safari
        - Other
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser(s) are you seeing the problem on?
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of our extension are you running?
    validations:
      required: true
  - type: checkboxes
    id: is-bug
    attributes:
      label: What are you doing?
      # description: What type of bug are you reporting?
      options:
        - label: I am reporting a bug
          required: true
    validations:
      required: true
